version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: npm install --safe
      - run:
          name: install supertest
          command: npm install supertest --save-dev
      - run:
          name: install mocha
          command: npm install mocha --save-dev
      - run:
          name: install chai
          command: npm install chai --save-dev
      - run:
          name: install joi           
          command: npm install joi --save-dev
      - run:
          name: install jot-assert
          command: npm install joi-assert --save-dev
      - run:
          name: install mochawesome
          command: npm install mochawesome --save-dev
      - run:
          name: install faker
          command: npm install faker --save-dev
      - run:
          name: pasta
          command: cd test
      - run:
          name: test
          command: mocha wirecard_test.js