version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm"
      - run:
          name: install-packages
          command: "sudo npm install -g"
      - run:
          name: find teste
          command: "cd test"
      - run:
          name: run test
          command: "mocha wirecard_test.js"
     