version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: npm install --safe
      - run:
          name: pasta
          command: cd test
      - run:
          name: test
          command: mocha wirecard_test.js